/**
 * Generated by scripts/build-linkedin-posts.mjs. Do not edit.
 *
 * Source: SmartCareliving/outreach/linkedin-drafts/*.md
 * Assets: public/outreach/linkedin/
 */

export interface LinkedInPost {
  n: string;
  title: string;
  hook: string;
  caption: string;
  tags: string[];
  video: string | null;
  still: string | null;
  close: string;
}

export const LINKEDIN_POSTS: LinkedInPost[] = [
  {
    "n": "01",
    "title": "The alarm that was never pressed",
    "caption": "In 97% of long lies, the alarm was never pressed.\n\nA Cambridge cohort study published in the BMJ followed older people who fell at home while they were alone. In 80% of those falls, the call alarm was not used. In 97% of long lies, meaning an hour or more on the floor, no alarm was activated at all.\n\nThe instinct is to say people forget to wear it. That is not what the number is describing.\n\nA pendant asks for a deliberate act from somebody who has just been injured, winded, disorientated, or knocked out. It asks for it at the one moment it is least likely to happen. It fails in precisely the circumstances that define a serious fall.\n\nThe hour on the floor is the part that changes the rest of it. In that same study, 60% of the people who had a long lie had a fall-related hospital admission within the year. 53% had moved into long-term care by the end of it.\n\nSo the question worth asking is not whether they have an alarm.\n\nIt is what happens at 3am if they cannot press it.\n\nIf you are looking after a parent who lives alone, here is something to check this week that costs nothing. Ask when the alarm was last tested. Then ask them, honestly, whether they would have reached it the last time they had a fright.\n\nWhat did they say?",
    "tags": [
      "#FallPrevention",
      "#AgeingInPlace",
      "#Ireland"
    ],
    "video": "/outreach/linkedin/pattern-fall.mp4",
    "still": "/outreach/linkedin/pattern-fall.png",
    "close": "question",
    "hook": "In 97% of long lies, the alarm was never pressed."
  },
  {
    "n": "02",
    "title": "What actually leaves the room",
    "caption": "There are two rooms families never allow a camera in. They are the two the sensor is most needed in.\n\nEvery family we speak to draws the line in the same two places. Not the bathroom, and not the bedroom. That is the right instinct, and it is also where a large share of serious falls happen, which is the whole problem with cameras.\n\nSo there is no video. The sensor reads the room and sends a stick figure. A shape, moving. That is what arrives on your phone and that is all that arrives.\n\nIt means the line families draw does not have to be drawn at all. The sensor can go where the risk actually is.\n\nWorth saying plainly, because people ask: there is no recording to be requested later, no footage to be leaked, and nothing a carer or a family member can scroll back through. The privacy is not a setting somebody could switch off by accident. It is what the thing sends.\n\nIf you are weighing this up for a parent, that distinction is the one to put to them directly. Most people who refuse a camera are not refusing help. They are refusing to be watched in their own bathroom, and they are right to.\n\nThis is how you offer the first without the second.",
    "tags": [
      "#AgeingInPlace",
      "#PrivacyByDesign"
    ],
    "video": "/outreach/linkedin/privacy-rooms.mp4",
    "still": "/outreach/linkedin/privacy-rooms.png",
    "close": "one line",
    "hook": "There are two rooms families never allow a camera in. They are the two the sensor is most needed in."
  },
  {
    "n": "03",
    "title": "Seven questions, and an actual specification",
    "caption": "Seven questions and two minutes gets you a specification, not a brochure.\n\nMost people researching home safety for a parent end up with a pile of product pages and no way to tell which of them applies to their situation. A pendant, a camera, a keysafe, a monitored alarm. All plausible. None of them answering the question you actually have, which is what should we do about Mum.\n\nSo the assessment asks seven things. Who you are helping. What has prompted you to look now. How independent they are today. What you are most worried about. What has already been tried. How soon you need to act.\n\nThen it tells you what it would put in, and where, and why.\n\nA recent fall produces a different answer from a slow decline. Somebody who is mostly independent gets a different setup from somebody who needs support with most things. That is the point. The recommendation moves because the situation moves.\n\nYou get the estimate at the end as well, not after a phone call. 549 for the first room, 349 for each room after that, 119 a month. Confirmed at a free home visit before anything is charged.\n\nNo salesperson rings you afterwards unless you ask one to.\n\nIt is at smartcareliving.ie, and it takes about as long as reading this did.",
    "tags": [
      "#AgeingInPlace",
      "#Ireland"
    ],
    "video": "/outreach/linkedin/assessment-flow.mp4",
    "still": "/outreach/linkedin/assessment-flow.png",
    "close": "one line",
    "hook": "Seven questions and two minutes gets you a specification, not a brochure."
  },
  {
    "n": "04",
    "title": "She does not have to reach anything",
    "caption": "She raises an arm and the call connects. There is no button anywhere in that sentence.\n\nWe have written before about the 97%, the share of older people who lay on the floor for an hour or more after a fall and never pressed their alarm. The figure is from a Cambridge study in the BMJ and it has been sitting in the literature since 2008.\n\nThe answer to it is usually framed as better detection. Catch the fall automatically, send help. That is half of it and it is the half everybody builds.\n\nThe other half is what somebody does when they are still upright and something is wrong. Feeling faint. Confused. Frightened at three in the morning and not sure why. There is no fall to detect yet, and a pendant is in a drawer or on a bedside table across the room.\n\nSo raising an arm calls you, and opens two way voice. She can talk to you from the floor, or from the chair, without finding or reaching or pressing anything at all.\n\nIt is a small thing to describe and it changes who the system works for. It works for somebody who would never have worn the pendant.\n\nIf you have had the pendant conversation with a parent and lost it, what was their actual objection?",
    "tags": [
      "#FallPrevention",
      "#AgeingInPlace",
      "#Ireland"
    ],
    "video": "/outreach/linkedin/arm-raise.mp4",
    "still": "/outreach/linkedin/arm-raise.png",
    "close": "question",
    "hook": "She raises an arm and the call connects. There is no button anywhere in that sentence."
  },
  {
    "n": "05",
    "title": "One in eight, in one year",
    "caption": "One in eight people aged over 70 in Ireland needed medical attention for a fall last year.\n\nThat is TILDA, the Irish Longitudinal Study on Ageing at Trinity College Dublin. Not an American figure borrowed and rounded. Ours.\n\nPut beside it the other number most people already accept: 75% of over fifties say they want to stay in their own home as they age.\n\nBoth of those are true at once, and the gap between them is where most families find themselves. Wanting to stay. Increasingly aware of what could end it.\n\nWhat usually happens is that nothing changes until something does. A fall, a hospital stay, a phone call at an unusual hour. The decision then gets made in a week, under pressure, by people who are frightened, and it is very often more drastic than it needed to be.\n\nThe alternative is unglamorous. Understand the house. Put sensors where the risk actually is rather than where they are easiest to fit. Learn what an ordinary week looks like in that specific home, so that a change in it is visible early, while there are still options.\n\nThat is the whole method and it is four steps. We do a free home visit first, and you get the specification and the price before anything is charged.\n\nStarting before the fall is the only version of this that leaves choices on the table.",
    "tags": [
      "#AgeingInPlace",
      "#Ireland",
      "#FallPrevention"
    ],
    "video": "/outreach/linkedin/how-we-work.mp4",
    "still": "/outreach/linkedin/how-we-work.png",
    "close": "one line",
    "hook": "One in eight people aged over 70 in Ireland needed medical attention for a fall last year."
  }
];
